### ISSUE TITLE
BBC World Service not integrated

### ISSUE THREAD

**Issue by jiri-janousek** [a-m-s/nuvola-app-bbc-iplayer#7]
Hello @a-m-s. The script seems to be broken. Could you look at it?

* Launch BBC iPlayer, go to menu → Load URL... → http://www.bbc.co.uk/radio/player/bbc_world_service
* No metadata is recognized.

**Comment by a-m-s** [comment]
Live radio (and TV) broadcasts of all kinds were not supported by WebkitGTK and therefore not integrated.

All radio stations should now work, including the World Service.

Live broadcasts just use the channel name and logo for the title. Programmes on the catch-up should have the proper name and artwork.

**Comment by jiri-janousek** [comment]
It still does not work. It used to work with WebKitGTK. I'll look at it.

**Comment by a-m-s** [comment]
I looked back at this and it did indeed not work; I got an integration error.

Then I had a look around other pages; still no integration, so I quit and reloaded.

Now it works perfectly. It's possible that something goes wrong when it comes up with the "Sign in" page, since that only happens first time in a clean install. I'll check that later.

**Comment by a-m-s** [comment]
I realised I forgot to push the patches I had. You can check again, although I think I may still have the clean install bug.

**Comment by a-m-s** [comment]
I can't reproduce the integration failure. It must have been something in a bad state, but not the first experience of every user that I feared.

I've confirmed, again, that the World Service is integrated. Please reopen if that's not true when accessed from outside the UK.

**Comment by jiri-janousek** [comment]
Thanks, I'll look at it :-)

**Comment by jiri-janousek** [comment]
Works great :+1:
